apiVersion: v1
kind: pod
metadata:
 name: env-demo
 labels:
   purpose: demonstarte-envars
spec:
 containers:
 - name: nginx
   image: nginx
   env:
   - name: COURSE
     value: "KUBERNETS"
   - name: TRAINER
     Value: "SATYAM"

     