CATALOGUE_HOST: catalogue.backend-{{ env }}.kimidi.site
CART_HOST: cart.backend-{{ env }}.kimidi.site
USER_HOST: user.backend-{{ env }}.kimidi.site
SHIPPING_HOST: shipping.backend-{{ env }}.kimidi.site
PAYMENT_HOST: payment.backend-{{ env }}.kimidi.site