#[frontend]
#.31.47.157 COURSE=Ansible DURATION=10HR TRAINER=Sivakumar ansible_user=ec2-user ansible_password=DevOps321


[local]
localhost

[mongodb]
mongodb.kimidi.site

[catalogue]
catalogue.kimidi.site

[frontend]
frontend.kimidi.site

[redis]
redis.kimidi.site
